---
language: python
python: "2.7"

sudo: required

os: linux

env:
  - SCENARIO=default
  - SCENARIO=ubuntu
  - SCENARIO=debian
  - SCENARIO=centos
  - SCENARIO=fedora

matrix:
  include:
    - os: osx
      language: generic

# Install Python and pip
before_install:
  - >-
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install python
      brew install md5sha1sum
      virtualenv venv -p python
      source venv/bin/activate
    fi
  - >-
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update
      sudo apt-get install -qq python-pip
      pip install -q molecule docker-py
    fi

install:
  # Install ansible
  - pip install -q ansible

  # Check ansible version
  - ansible --version

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then molecule test --scenario-name $SCENARIO; fi
  - >-
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # Create ansible.cfg with correct roles_path
      printf '[defaults]\nroles_path=../' >ansible.cfg
      # Install dependencies (for syntax check and installation)
      ansible-galaxy install --roles-path ../ andrewrothstein.anaconda
      # Syntax check
      ansible-playbook tests/test.yml -i tests/inventory --syntax-check
      # Install role
      ansible-playbook tests/test.yml -i tests/inventory
    fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
