---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: fedora_27
    image: fedora:27
  - name: fedora_26
    image: fedora:26
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: fedora
verifier:
  name: testinfra
  lint:
    name: flake8
