---
- name: Add Anaconda to sudoers path
  become: yes
  lineinfile:
    path: /etc/sudoers
    regexp: 'secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"'
    backrefs: yes
    line: 'Defaults	secure_path="/usr/local/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"'
    validate: '/usr/sbin/visudo -cf %s'
  when: data_science_base_anaconda_make_sys_default

- name: Install dependencies of Spyder on Debians
  become: yes
  apt:
    name: python3-pyqt5
  when: ansible_os_family == 'Debian'

- name: Install dependencies of Spyder on OS X
  become: yes
  homebrew:
    name: python3-pyqt5
  when: ansible_os_family == 'Darwin'

- name: Install spyder notebook
  become: yes
  shell: conda install spyder-notebook -c spyder-ide

- name: Install keras
  become: yes
  shell: conda install -y keras

#- name: Install sklearn_pandas
#  become: yes
#  pip:
#    name: sklearn-pandas
  
- name: Install Graphviz binaries for Debians
  become: yes
  apt:
    name: graphviz
  when: ansible_os_family == 'Debian'

- name: Install Graphviz binaries for OS X
  become: yes
  homebrew:
    name: graphviz
  when: ansible_os_family == 'Darwin'

- name: Install Graphviz python bindings
  become: yes
  pip:
    name: graphviz

- name: Configure Jupyter
  import_tasks: jupyter.yml
  vars:
    - anaconda_bin_path: '{{ anaconda_install_dir }}/bin'
