---
- name: Load OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - 'default.yml'

- name: Add Anaconda to sudoers path
  become: yes
  lineinfile:
    path: /etc/sudoers
    regexp: 'secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"'
    backrefs: yes
    line: 'Defaults	secure_path="/usr/local/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"'
    validate: '/usr/sbin/visudo -cf %s'
  when: data_science_base_anaconda_make_sys_default

- name: Install dependencies of Spyder
  become: '{{ data_science_base_os_dependent_package_become }}'
  package:
    name: '{{ data_science_base_os_dependent_pyqt5_package_name }}'

- name: Install spyder notebook
  become: yes
  command: '{{anaconda_link_dir}}/bin/conda install spyder-notebook -c spyder-ide'

- name: Install keras
  become: yes
  command: '{{anaconda_link_dir}}/bin/conda install -y keras'

#- name: Install sklearn_pandas
#  become: yes
#  pip:
#    name: sklearn-pandas
  
- name: Install Graphviz binaries
  become: '{{ data_science_base_os_dependent_package_become }}'
  package:
    name: graphviz

- name: Install Graphviz python bindings
  become: yes
  pip:
    name: graphviz

- name: Configure Jupyter
  import_tasks: jupyter.yml
  vars:
    - anaconda_bin_path: '{{ anaconda_link_dir }}/bin'
