---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos_7
    image: centos:7
  - name: centos_6
    image: centos:6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: centos
verifier:
  name: testinfra
  lint:
    name: flake8
